---

images:
  pod_infra: # registry.access.redhat.com/rhel7/pod-infrastructure
    name: pause
    repos: registry.docker-cn.com/zw12078/
    tag: "3.0"
  apiserver:
    name: kube-apiserver-amd64
    repos: registry.docker-cn.com/zw12078/
    tag: "v{{ kube_version }}"
  manager: # 'quay.io/attcomdev/kube-controller-manager:v{{ kube_version }}' for ceph storage class
    name: kube-controller-manager-amd64
    repos: registry.docker-cn.com/zw12078/
    tag: "v{{ kube_version }}"
  scheduler:
    name: kube-scheduler-amd64
    repos: registry.docker-cn.com/zw12078/
    tag: "v{{ kube_version }}"
  haproxy:
    name: haproxy
    repos: registry.docker-cn.com/kairen/
    tag: "1.7"
  keepalived:
    name: keepalived
    repos: registry.docker-cn.com/kairen/
    tag: "1.2.24"
  registry:
    name: registry
    repos: registry.docker-cn.com/kairen/
    tag: "2.6.1"
  registry_ui:
    name: docker-registry-ui
    repos: registry.docker-cn.com/parabuzzle/
    tag: "2.1.3"
  repos:
    name: pkg-repos
    repos: registry.docker-cn.com/kairen/
    tag: "0.1.0"
  flannel:
    name: kube-flannel
    repos: registry.docker-cn.com/zw12078/kube-flannel
    tag: "v0.9.1"
  calico:
    name: calico-node
    repos: registry.docker-cn.com/zw12078/calico-node
    tag: "v2.6.2"